server:
  servlet:
    context-path: /sell
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.9/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  freemarker:
    suffix: .ftl
  redis:
    host: 192.168.1.9
    port: 6379
  data:
    redis:
      repositories:
        enabled: false
wechat:
  weAppId: wx093c72359ab3e8dc
  weAppSecret: 5bb8701228f79a96e0bc07710f8af8c8
  openAppid:
  openAppSecret:
  mchId: 1409146202
  mchKey: 0976503d34ca432c601361f969fd8d85
  keyPath: F:/weixin_cert/h5.p12
  notifyUrl: http://redbtree.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: X6Z49ARrcHmGobVkxyts-YH2KjuAHh6OAiQi2vDMmJE
project:
  wxMpAuthorizeUrl: http://redbtree.natapp4.cc
  wxOpenAuthorizeUrl: http://redbtree.natapp4.cc
  sell: http://redbtree.natapp4.cc