server:
  servlet:
    context-path: /sell
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.11/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  freemarker:
    suffix: .ftl
wechat:
  weAppId: wx093c72359ab3e8dc
  weAppSecret: 5bb8701228f79a96e0bc07710f8af8c8
  mchId: 1409146202
  mchKey: 0976503d34ca432c601361f969fd8d85
  keyPath: F:/weixin_cert/h5.p12
  notifyUrl: http://redbtree.natapp4.cc/sell/pay/notify
